#!/bin/sh

# -- keybindings --

# Launch applications/shortcuts
riverctl map normal Super Return spawn foot
riverctl map normal Super D spawn 'rofi -show drun'

# MOD
mod="Mod4"

# window management/shortcuts
riverctl map normal $mod Q close
riverctl map normal Super+Shift Return zoom
riverctl map normal Super+Shift Down swap next
riverctl map normal Super+Shift Up swap previous
riverctl map normal Super Down focus-view next
riverctl map normal Super Up focus-view previous

# pointer actions
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super+Shift f toggle-float

# screenshot
riverctl map normal None Print spawn 'hyprshot-gui'

#  brightness and vol controls 

for mode in normal locked; do
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
    riverctl map $mode None XF86AudioRaiseVolume spawn 'amixer -D pulse sset Master 5%+'
    riverctl map $mode None XF86AudioLowerVolume spawn 'amixer -D pulse sset Master 5%-'
    riverctl map $mode None XF86AudioMute        spawn 'amixer -D pulse set Master 1+ toggle'
    riverctl map-switch $mode lid close spawn 'wlr-randr --output eDP-1 --off'
    riverctl map-switch $mode lid open spawn 'wlr-randr --output eDP-1 --on'
done

#  Tag Management 

for i in $(seq 1 9); do
    tags=$((1 << (i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
done

#  Visual Settings 

swww img --transition-type grow --transition-fps 255 /home/alex/walls/wallpaper.jpeg
riverctl xcursor-theme nixutomata

#  Input Settings

riverctl set-repeat 40 300
riverctl hide-cursor when-typing enabled
riverctl focus-follows-cursor always
riverctl set-cursor-warp on-focus-change

riverctl input pointer-961030-Pine64_Pinebook_Pro_Touchpad tap enabled
riverctl input pointer-9610-30-Pine64_Pinebook_Pro_Touchpad natural-scroll enabled
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_LEFT move-view

# -- touchpad
for pad in $(riverctl list-inputs | grep -i touchpad )
do
  riverctl input $pad events enabled
  riverctl input $pad tap enabled
done

# -- Startup Applications --
# riverctl spawn mako
riverctl spawn dunst
riverctl spawn swww-daemon
riverctl spawn waybar
